
# configファイルの保存先なので忘れず変更する
hydra:
  run:
    dir: outputs/ours_baseline5


# 手法独自のハイパラ
method:
  name: lsf



# log関連
log:
  name: 
  base: "baseline"
  model: "model"
  result: "result"
  base_path: 
  model_path: 
  explog_path: 
  mem_path: 
  result_path: 



# データセット関連
dataset:
  type: "cifar10"
  size: 32
  num_class: 10
  data_folder: '/home/kouyou/datasets/'

# 継続学習の問題設定関連
continual:
  num_task: 5
  cls_per_task: 2
  output_size: [2, 2, 2, 2, 2]
  target_task: 


# 最適化手法関連
optimizer:
  train:
    learning_rate: 0.1
    momentum: 0.9
    weight_decay: 5e-4
    batch_size: 128
    epoch: 
    base_epoch: 20
    add_epoch: 20


scheduler:
  type: "cosine"
  lr_decay_rate: 0.01
  warmup: True
  warmup_epochs: 10
  warmup_from: 0.001
  warmup_to: 



seed: 0
num_workers: 8
date: 2025_1116

